CREATE TABLE TEST (
    TEST_NO NUMBER PRIMARY KEY,
    TEST_GUID RAW(16)UNIQUE,
    TEST_ID VARCHAR2(30) NOT NULL UNIQUE,
    TEST_PWD VARCHAR2(30) NOT NULL,
    TEST_ROLL VARCHAR2(10) DEFAULT 'TEST_USER',
    TEST_NAME VARCHAR2(20) NOT NULL,
    PHONE VARCHAR2(13),
    ADDRESS VARCHAR2(30),
    ENROLL_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR(1) DEFAULT 'Y' CHECK(STATUS IN('Y','N'))
);

COMMENT ON COLUMN TEST.TEST_NO IS '테스트번호';
COMMENT ON COLUMN TEST.TEST_GUID IS '테스트GUID';
COMMENT ON COLUMN TEST.TEST_ID IS '아이디';
COMMENT ON COLUMN TEST.TEST_PWD IS '비밀번호';
COMMENT ON COLUMN TEST.TEST_ROLL IS '타입';
COMMENT ON COLUMN TEST.TEST_NAME IS '이름';
COMMENT ON COLUMN TEST.PHONE IS '휴대전화';
COMMENT ON COLUMN TEST.ADDRESS IS '주소';
COMMENT ON COLUMN TEST.ENROLL_DATE IS '생성날짜';
COMMENT ON COLUMN TEST.MODIFY_DATE IS '수정날짜';
COMMENT ON COLUMN TEST.STATUS IS '상태값(Y/N)';

CREATE SEQUENCE SEQ_UNO;

INSERT INTO TEST 
VALUES(
    SEQ_UNO.NEXTVAL,
    SYS_GUID(),
    'admin',
    '1234',
    '관리자',
    '김정현',
    '010-7343-9339',
    '서울',
    SYSDATE,
    SYSDATE,
    DEFAULT
);

COMMIT;
